// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZwm6942Gfhdvvq0hxyPCIESCDdJ5Yhs',
    appId: '1:623162670259:android:5d3cde1811f5bd1e9504c6',
    messagingSenderId: '623162670259',
    projectId: 'accountingdevapp',
    databaseURL: 'https://accountingdevapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'accountingdevapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENgbv92YrfWXxSHqQ6zLljDOoBB9aZMY',
    appId: '1:623162670259:ios:57b71d910814fc879504c6',
    messagingSenderId: '623162670259',
    projectId: 'accountingdevapp',
    databaseURL: 'https://accountingdevapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'accountingdevapp.appspot.com',
    androidClientId: '623162670259-5c6b5bhjmrkqdim230gcj5cmp0a4jdgh.apps.googleusercontent.com',
    iosClientId: '623162670259-el3e240cjoe6ahmnjqu28khnisgep9k7.apps.googleusercontent.com',
    iosBundleId: 'com.trustmedia.accounting',
  );

}